'use client';

import React, { useState, useEffect } from 'react';
import { StravaActivity } from '@/types/strava';
import { ProcessedStats } from '@/types/stats';
import { getLevelInfo } from '@/lib/xpSystem';
import {
  computeRoles, computeObjectiveAfinidad, computeObjectiveChecklist,
  RoleObjective, BranchResult,
} from '@/lib/roles';
import {
  Card,
  LevelSection,
  RoleHeading,
  RoleNamePrimary,
  LevelBadge,
  XpRow,
  XpTrack,
  XpFill,
  XpLabel,
  XpSummary,
  RolesSection,
  RolesSectionTitle,
  PrimaryRoleCard,
  PrimaryMedalLabel,
  PrimaryRoleName,
  PrimaryRoleBranch,
  PrimaryAfinidadRow,
  PrimaryAfinidadTrack,
  PrimaryAfinidadFill,
  PrimaryAfinidadPct,
  SecondaryRolesList,
  SecondaryRoleRow,
  SecondaryMedalDot,
  SecondaryRoleInfo,
  SecondaryRoleName,
  SecondaryRoleBranch,
  SecondaryAfinidad,
  ObjectiveSection,
  ObjectiveSectionTitle,
  ObjectiveBtns,
  ObjectiveBtn,
  ObjectiveProgress,
  ObjectiveAfinidadRow,
  ObjectiveAfinidadLabel,
  ObjectiveAfinidadTrack,
  ObjectiveAfinidadFill,
  ObjectiveAfinidadPct,
  ObjectiveHowTo,
  ChecklistRow,
  ChecklistChip,
} from './styled';

const OBJECTIVE_LABELS: Record<RoleObjective, string> = {
  maratonista: 'Maratonista',
  velocista: 'Velocista',
  conquistador: 'Conquistador',
  medallista: 'Medallista',
};

const BRANCH_LABELS: Record<string, string> = {
  distance: 'Distancia',
  speed: 'Velocidad',
  exploration: 'Exploración',
  achievement: 'Logros',
};

type SecondaryRank = 'silver' | 'bronze' | 'none';

interface PersonajeCardProps {
  activities: StravaActivity[];
  stats: ProcessedStats;
}

const STORAGE_KEY = 'platenzen_role_objective';

const PersonajeCard: React.FC<PersonajeCardProps> = ({ activities, stats }) => {
  const [objective, setObjective] = useState<RoleObjective | null>(null);

  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) setObjective(stored as RoleObjective);
  }, []);

  const levelInfo = getLevelInfo(activities, stats);
  const roles = computeRoles(activities, stats);

  // Sort branches: primary first, then by afinidad desc
  const sortedBranches = [...roles.branches].sort((a, b) => {
    const levelDiff = b.currentRole.level - a.currentRole.level;
    return levelDiff !== 0 ? levelDiff : b.afinidad - a.afinidad;
  });

  const primary = sortedBranches[0];
  const secondaries = sortedBranches.slice(1);

  const handleObjective = (obj: RoleObjective) => {
    const newObj = obj === objective ? null : obj;
    setObjective(newObj);
    if (newObj) localStorage.setItem(STORAGE_KEY, newObj);
    else localStorage.removeItem(STORAGE_KEY);
  };

  const objectiveResult = objective ? computeObjectiveAfinidad(objective, roles) : null;

  const xpLabel = levelInfo.nextThreshold
    ? `${levelInfo.xp.toLocaleString('es-AR')} / ${levelInfo.nextThreshold.toLocaleString('es-AR')} XP`
    : `${levelInfo.xp.toLocaleString('es-AR')} XP`;

  return (
    <Card>
      {/* ── Identity header ── */}
      <LevelSection>
        <RoleHeading>
          <RoleNamePrimary>{primary.currentRole.name}</RoleNamePrimary>
          <LevelBadge>(Nivel {levelInfo.level})</LevelBadge>
        </RoleHeading>
        <XpRow>
          <XpTrack>
            <XpFill $pct={levelInfo.progress} />
          </XpTrack>
          <XpLabel>{xpLabel}</XpLabel>
        </XpRow>
        {/* xpSourceSummary contains <strong> tags generated by lib/xpSystem.ts */}
        <XpSummary dangerouslySetInnerHTML={{ __html: levelInfo.breakdown.xpSourceSummary }} />
      </LevelSection>

      {/* ── Roles ── */}
      <RolesSection>
        <RolesSectionTitle>Perfil de corredor</RolesSectionTitle>

        {/* Primary role — prominent */}
        <PrimaryRoleCard>
          <PrimaryMedalLabel>Rol principal</PrimaryMedalLabel>
          <PrimaryRoleName>{primary.currentRole.name}</PrimaryRoleName>
          <PrimaryRoleBranch>{BRANCH_LABELS[primary.branch]}</PrimaryRoleBranch>
          <PrimaryAfinidadRow>
            <PrimaryAfinidadTrack>
              <PrimaryAfinidadFill $pct={primary.afinidad} />
            </PrimaryAfinidadTrack>
            <PrimaryAfinidadPct>Afinidad {primary.afinidad}%</PrimaryAfinidadPct>
          </PrimaryAfinidadRow>
        </PrimaryRoleCard>

        {/* Secondary roles — compact list */}
        {secondaries.length > 0 && (
          <SecondaryRolesList>
            {secondaries.map((br, i) => {
              const rank: SecondaryRank = i === 0 ? 'silver' : i === 1 ? 'bronze' : 'none';
              return (
                <SecondaryRoleItem key={br.branch} branch={br} rank={rank} />
              );
            })}
          </SecondaryRolesList>
        )}
      </RolesSection>

      {/* ── Objective selector ── */}
      <ObjectiveSection>
        <ObjectiveSectionTitle>Objetivo de personaje</ObjectiveSectionTitle>

        <ObjectiveBtns>
          {(Object.keys(OBJECTIVE_LABELS) as RoleObjective[]).map(obj => (
            <ObjectiveBtn
              key={obj}
              $active={objective === obj}
              onClick={() => handleObjective(obj)}
            >
              {OBJECTIVE_LABELS[obj]}
            </ObjectiveBtn>
          ))}
        </ObjectiveBtns>

        {objective && objectiveResult && (
          <ObjectiveProgress>
            <ObjectiveAfinidadRow>
              <ObjectiveAfinidadLabel>
                Afinidad con {OBJECTIVE_LABELS[objective]}
              </ObjectiveAfinidadLabel>
              <ObjectiveAfinidadTrack>
                <ObjectiveAfinidadFill $pct={objectiveResult.afinidad} />
              </ObjectiveAfinidadTrack>
              <ObjectiveAfinidadPct>{objectiveResult.afinidad}%</ObjectiveAfinidadPct>
            </ObjectiveAfinidadRow>
            <ObjectiveChecklist objective={objective} activities={activities} stats={stats} />
          </ObjectiveProgress>
        )}

        {!objective && (
          <ObjectiveHowTo style={{ color: 'var(--text-muted)', fontSize: '0.78rem' }}>
            Elegí un objetivo para ver qué aspectos del entrenamiento conviene potenciar.
          </ObjectiveHowTo>
        )}
      </ObjectiveSection>
    </Card>
  );
};

// ── Objective checklist ────────────────────────────────────────────────────

interface ObjectiveChecklistProps {
  objective: RoleObjective;
  activities: StravaActivity[];
  stats: ProcessedStats;
}

const ObjectiveChecklist: React.FC<ObjectiveChecklistProps> = ({ objective, activities, stats }) => {
  const items = computeObjectiveChecklist(objective, activities, stats);
  return (
    <ChecklistRow>
      {items.map((item, i) => (
        <ChecklistChip key={i} $passed={item.passed}>
          {item.passed ? '✓' : '⬜'} {item.label}
        </ChecklistChip>
      ))}
    </ChecklistRow>
  );
};

// ── Secondary role compact row ─────────────────────────────────────────────

const RANK_LABEL: Record<SecondaryRank, string> = {
  silver: 'Afinidad alta',
  bronze: 'Afinidad media',
  none: '',
};

interface SecondaryRoleItemProps {
  branch: BranchResult;
  rank: SecondaryRank;
}

type SecondaryRank2 = 'silver' | 'bronze' | 'none';

const SecondaryRoleItem: React.FC<SecondaryRoleItemProps> = ({ branch, rank }) => {
  const rankLabel = RANK_LABEL[rank as SecondaryRank2];
  return (
    <SecondaryRoleRow>
      <SecondaryMedalDot $rank={rank} />
      <SecondaryRoleInfo>
        <SecondaryRoleName>{branch.currentRole.name}</SecondaryRoleName>
        <SecondaryRoleBranch>
          {BRANCH_LABELS[branch.branch]}
          {rankLabel ? ` · ${rankLabel}` : ''}
        </SecondaryRoleBranch>
      </SecondaryRoleInfo>
      <SecondaryAfinidad>{branch.afinidad}%</SecondaryAfinidad>
    </SecondaryRoleRow>
  );
};

export default PersonajeCard;
